version: '3.8'

services:
  frontend:
    image: 2.4-frontend
    build: ./frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    image: 2.4-backend
    build: ./backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=cache
  cache:
    image: docker.io/library/redis:7.0
    container_name: redis