version: '3.8'

services:
  frontend:
    image: 2.3-frontend
    build: ./frontend
    ports:
      - 5000:5000
    container_name: 2.3-frontend
  backend:
    image: 2.3-backend
    build: ./backend
    ports:
      - 8080:8080
    container_name: 2.3-backend